services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_sentinel
    ports:
      - "4566:4566"            # Porta principal para os serviços AWS
      - "4510-4559:4510-4559"  # Range para serviços externos (opcional, mas bom ter)

    environment:
      # Aqui definimos quais serviços da AWS queremos que o LocalStack inicie.
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
